### PR TITLE
add more apple targets c_char type definition

### PR DESCRIPTION
**Pull request by DrGlaucous**

### CODE REVIEW

**Comment by Lokathor** [comment]
Hello, hi. This crate is so old I'd forgotten it was around. in like Rust 1.64 they moved a lot of ffi types into core:
https://doc.rust-lang.org/nightly/core/ffi/type.c_char.html

Would you mind saying which project is still using the `chlorine` crate? I think that, in general, everyone should be using the `core::ffi` definitions at this point. I'm surprised anyone still uses this.

**Comment by DrGlaucous** [comment]
I would switch to using the mainline `core::ffi` definitions if I could, but the library I'm working with depends on [imgui-rs](https://github.com/imgui-rs/imgui-rs/tree/main), which still uses chlorine for some of these definitions. 

Specifically, here:
https://github.com/imgui-rs/imgui-rs/blob/main/imgui-sys/Cargo.toml

I'm working on several ports of doukutsu-rs, a Cave Story engine rewrite, which was actually made by the same person who opened this pull request earlier this year: https://github.com/Lokathor/chlorine/pull/6

**Comment by Lokathor** [comment]
Okay. I'll merge this and issue the crates.io release, an then I'll see about doing a PR to imgui so that they stop using chlorine. their readme says they use rust 1.70 as the minimum, so it shouldn't be too hard to convince them.

**Comment by Lokathor** [comment]
published `chlorine-1.0.13`, and opened https://github.com/imgui-rs/imgui-rs/pull/818

**Pull request merged**
